#!/usr/bin/env bash
# bash scriptto transfer files to server with scp
if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~
fi