#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y nginx

# ENABLING FIREWALL RULES
sudo ufw allow 'Nginx HTTP'
# sudo ufw allow 'OpenSSH'
# sudo ufw enable


echo "Hello World!" |sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
