#!/usr/bin/env bash
# This is a bash script to make a custom 404 error page
sudo apt-get update
sudo apt-get install -y nginx

# ENABLING FIREWALL RULES
sudo ufw allow 'Nginx HTTP'
# sudo ufw allow 'OpenSSH'
# sudo ufw enable

# create error webpage and default page
echo "Ceci n'est pas une page" |sudo tee /var/www/html/404.html
echo "Hello World!" |sudo tee /var/www/html/index.nginx-debian.html

nginx_setup="server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
            try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location  /404.html {
        root /var/www/html;
        internal;
    }

}"

echo -e "$nginx_setup" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
