#!/usr/bin/env bash
# script to automate configuration of Nginx server (http response)
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo sed -t "/http /a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf

sudo service nginx restart
