#!/usr/bin/env bash
# script to automate configuration of Nginx server (http response)
sudo apt-get update
sudo apt-get -y install nginx

sudo ufw allow 'Nginx HTTP'

sudo sed -i '/server_name _;/a\\    add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

sudo service nginx restart
