#!/usr/bin/env bash
# script to automate setup and installation of HAProxy

sudo apt-get -y update

sudo apt-get -y install software-properties-common

sudo add-apt repository -y ppa:vbernat/haproxy-2.0
sudo app-get -y update
sudo apt-get -y install haproxy

balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend my_webservers

backend webservers
    balance roundrobin
    server 234523-web-01 18.234.105.167:80 check
    server 234523-web-02 100.25.222.179:80 check
"
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" |sudo tee /etc/haproxy/haproxy.cfg

sudo service haproxy start

