#!/usr/bin/env bash
# script to automate setup and installation of HAProxy

#update and upgrade
sudo apt-get update
sudo apt-get -y upgrade 

#install dependencies and HAProxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y install haproxy=2.8\*


config="\
frontend lb_1
    bind *:80
    mode http
    default_backend web_backend

backend web_backend
    balance roundrobin
    mode http
    server 297169-web-01 34.207.83.139:80 check
    server 297169-web-02 54.89.37.157:80 check

"

#create backup of default config
sudo cp -a /etc/haproxy/haproxy.cfg{,.default_copy}

#add desired configuration and enable HAProxy to be started by the init script
echo "$config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart

