#!/usr/bin/env bash
# while loop printing a line of text 10 times

i=0
while  [ $i -lt 10 ]
do
    if [[ $i -eq 8 ]]; then
        echo "Hi"
    else
        echo "Best School"
    fi
    i=$(( i+1 ))
done
