#!/usr/bin/env bash
# while loop printing a line of text 10 times

i=0
while  [ $i -lt 10 ]
do
    if [[ $i -eq 7 ]]; then
        echo ""good luck
    elif [[ $i -eq 3 ]]; then
        echo "bad luck"
    else
        echo "Best School"
    fi
    i=$(( i+1 ))
done
