#!/usr/bin/env bash
# bash script displaying time for 12hrs 59 min

i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"

    j=1
    while [ $j -le 59 ]
    do
        echo "$j"
        (( j++ ))
    done
    (( i++ ))
done