#!/usr/bin/env bash

#give info on `school` file

if [ -e "school" ]; then
    echo "school file exists"

    if [ ! -s "school" ]; then
        echo "school file is empty"
    elif [ -s "school" ]; then
        echo "school file is not empty"
    elif [ -f "school" ]; then
        echo "school is a regular file"
    fi

else
    echo "school file does not exist"
fi