#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get -y install ufw
sudo ufw disable
sudo default deny incoming
sudo default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 44333/tcp
sudo ufw allow 80/tcp
sudo ufw enable
sudo ufw status
