#!/usr/bin/env bash
# script to change the IP address of localhost and facebook

cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
echo "8.8.8.8        facebook.com" >> ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts